services:
  - type: web
    name: stock-prediction-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GRADIO_PORT
        value: "7860"
      - key: SUPABASE_URL
        sync: false # Set manually in dashboard: https://gxtlqnrevmdvlggwjloz.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false # Set this manually in the dashboard
      - key: SUPABASE_REQUIRED
        value: "true" # Set to "true" if you want to fail health checks when Supabase is down
    healthCheckPath: /health
    numInstances: 1
    region: oregon
    autoDeploy: true 