# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app's secrets section
# Go to: share.streamlit.io → Your App → Settings → Secrets

[secrets]
# Supabase Configuration
# Get these values from your Supabase project dashboard (Settings → API)
SUPABASE_URL = "https://gxtlqnrevmdvlggwjloz.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4dGxxbnJldm1kdmxnZ3dqbG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDczODYsImV4cCI6MjA2NjU4MzM4Nn0.QETOPuqx8Yvk8zhkLncZy1zHRUhbTBODvnXree-aqAM"
SUPABASE_REQUIRED = "true"

# Optional: Database configuration
# Set to "true" if you want the app to fail when Supabase is unavailable
# SUPABASE_REQUIRED = "true"

# Example with actual values (replace with your own):
# SUPABASE_URL = "https://gxtlqnrevmdvlggwjloz.supabase.co"
# SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
# SUPABASE_REQUIRED = "false" 